### ISSUE TITLE
Incompatible with "avast! Online Security" (and others) due to data: image versus about:blank

### ISSUE THREAD

**Issue by Logopher** [Jman/lazy_tab#2]
At chrome://extensions I get this error for my Avast extension:

Warning:
This extension failed to redirect a network request to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAFElEQVR4XgXAAQ0AAABAMP1L30IDCPwC/o5WcS4AAAAASUVORK5CYII= because another extension (Lazy Tabs) redirected it to about:blank.

Researching, I found that there's apparently a conventional data: URL for this purpose among extension developers, but it's not the one Avast uses. See here:

http://forum.avast.com/index.php?topic=137248.0

I don't understand why the image is better than about:blank, but if it's a widespread convention I suppose that's the best option. Unfortunately, I don't think there's any right way to become compatible with Avast... but I don't think it's crippled by this conflict, either.

**Comment by Jman** [comment]
Algorithm was changed in 0.4.0
