### ISSUE TITLE
Error in event handler for tabs.onUpdated: TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ghost** [Jman/lazy_tab#3]
![lazy_tab1of2](https://cloud.githubusercontent.com/assets/5661825/4180578/4acfd01e-36fd-11e4-958a-3526b601a3c9.png)
![lazy_tab2of2](https://cloud.githubusercontent.com/assets/5661825/4180583/503a05a6-36fd-11e4-8d0a-593814f45976.png)

I don't know when this happens, just happened to look and saw that before disabling it.
Chromium Version 39.0.2145.4 (8f3c881c091a8eb8bc9df2ed45e11a4ed35e628a) (64-bit)

**Comment by Jman** [comment]
Algorithm was changed in 0.4.0
