### ISSUE TITLE
Conflict with AdBlock

### ISSUE THREAD

**Issue by liry** [Jman/lazy_tab#4]
Conflict with AdBlock extension (e.g. version 2.38). Consumes a lot of CPU and shows error messages like:

> Warning:
> This extension failed to redirect a network request to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACklEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg== because another extension (Lazy Tabs) redirected it to about:blank.

**Comment by Jman** [comment]
Algorithm was changed in 0.4.0
